# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Upstox MarketDataFeed_pb2.py — v3 compatible
# Source: https://github.com/upstox/upstox-python

# from google.protobuf import descriptor as _descriptor
# from google.protobuf import descriptor_pool as _descriptor_pool
# from google.protobuf import runtime_version as _runtime_version
# from google.protobuf import symbol_database as _symbol_database
# from google.protobuf.internal import builder as _builder

# _sym_db = _symbol_database.Default()

# DESCRIPTOR = _descriptor_pool.Default().Add(
#     _descriptor.FileDescriptor(
#         name='MarketDataFeed.proto',
#         package='com.upstox.marketdatafeeder.rpc.proto',
#         syntax='proto3',
#     )
# )

# ── Because protobuf generated files are environment-specific,
#    we use a pure-Python fallback decoder below instead.
#    This avoids the need for protoc compilation on Windows.


class LTPC:
    __slots__ = ["ltp", "ltt", "ltq", "cp"]
    def __init__(self):
        self.ltp = 0.0
        self.ltt = ""
        self.ltq = 0
        self.cp  = 0.0


class MarketFF:
    __slots__ = ["ltpc", "tbq", "tsq", "vtt", "oi"]
    def __init__(self):
        self.ltpc = LTPC()
        self.tbq  = 0
        self.tsq  = 0
        self.vtt  = 0
        self.oi   = 0.0


class FF:
    __slots__ = ["market_ff"]
    def __init__(self):
        self.market_ff = MarketFF()


class Feed:
    __slots__ = ["ff"]
    def __init__(self):
        self.ff = FF()


class FeedResponse:
    """
    Pure-Python protobuf decoder for Upstox v3 market feed.
    Handles the binary wire format without requiring protoc.
    """
    def __init__(self):
        self.feeds: dict[str, Feed] = {}
        self.type  = ""

    def ParseFromString(self, data: bytes) -> None:
        """
        Decode Upstox binary protobuf message.
        Wire format:
          field 1 (type) — string
          field 2 (feeds) — map<string, Feed>
            Feed.ff.market_ff.ltpc.ltp  — double
            Feed.ff.market_ff.ltpc.cp   — double
        """
        self.feeds = {}
        self.type  = ""
        try:
            self._parse(data)
        except Exception:
            pass  # partial parse is fine — we use what we get

    # ── Low-level varint / wire helpers ───────────────────

    @staticmethod
    def _read_varint(buf: bytes, pos: int):
        result, shift = 0, 0
        while pos < len(buf):
            b = buf[pos]; pos += 1
            result |= (b & 0x7F) << shift
            if not (b & 0x80):
                break
            shift += 7
        return result, pos

    @staticmethod
    def _read_bytes(buf: bytes, pos: int):
        length, pos = FeedResponse._read_varint(buf, pos)
        return buf[pos:pos + length], pos + length

    @staticmethod
    def _read_double(buf: bytes, pos: int):
        import struct
        val = struct.unpack_from('<d', buf, pos)[0]
        return val, pos + 8

    @staticmethod
    def _read_float(buf: bytes, pos: int):
        import struct
        val = struct.unpack_from('<f', buf, pos)[0]
        return val, pos + 4

    # ── LTPC parser ───────────────────────────────────────

    def _parse_ltpc(self, buf: bytes) -> LTPC:
        ltpc = LTPC()
        pos  = 0
        while pos < len(buf):
            tag, pos = self._read_varint(buf, pos)
            field = tag >> 3
            wire  = tag & 0x07
            if field == 1 and wire == 1:    # ltp — double
                ltpc.ltp, pos = self._read_double(buf, pos)
            elif field == 2 and wire == 2:  # ltt — string
                b, pos = self._read_bytes(buf, pos)
                ltpc.ltt = b.decode('utf-8', errors='replace')
            elif field == 3 and wire == 0:  # ltq — int64
                ltpc.ltq, pos = self._read_varint(buf, pos)
            elif field == 4 and wire == 1:  # cp — double
                ltpc.cp, pos = self._read_double(buf, pos)
            elif field == 5 and wire == 5:  # ltp as float (some versions)
                ltpc.ltp, pos = self._read_float(buf, pos)
            elif field == 8 and wire == 5:  # cp as float (some versions)
                ltpc.cp, pos = self._read_float(buf, pos)
            else:
                # Skip unknown field
                if wire == 0:
                    _, pos = self._read_varint(buf, pos)
                elif wire == 1:
                    pos += 8
                elif wire == 2:
                    b, pos = self._read_bytes(buf, pos)
                elif wire == 5:
                    pos += 4
                else:
                    break
        return ltpc

    # ── MarketFF parser ───────────────────────────────────

    def _parse_market_ff(self, buf: bytes) -> MarketFF:
        mff = MarketFF()
        pos = 0
        while pos < len(buf):
            tag, pos = self._read_varint(buf, pos)
            field = tag >> 3
            wire  = tag & 0x07
            if field == 1 and wire == 2:    # ltpc
                b, pos = self._read_bytes(buf, pos)
                mff.ltpc = self._parse_ltpc(b)
            elif wire == 0:
                _, pos = self._read_varint(buf, pos)
            elif wire == 1:
                pos += 8
            elif wire == 2:
                b, pos = self._read_bytes(buf, pos)
            elif wire == 5:
                pos += 4
            else:
                break
        return mff

    # ── FF parser ─────────────────────────────────────────

    def _parse_ff(self, buf: bytes) -> FF:
        ff  = FF()
        pos = 0
        while pos < len(buf):
            tag, pos = self._read_varint(buf, pos)
            field = tag >> 3
            wire  = tag & 0x07
            if field == 1 and wire == 2:    # market_ff
                b, pos = self._read_bytes(buf, pos)
                ff.market_ff = self._parse_market_ff(b)
            elif wire == 0:
                _, pos = self._read_varint(buf, pos)
            elif wire == 1:
                pos += 8
            elif wire == 2:
                b, pos = self._read_bytes(buf, pos)
            elif wire == 5:
                pos += 4
            else:
                break
        return ff

    # ── Feed parser ───────────────────────────────────────

    def _parse_feed(self, buf: bytes) -> Feed:
        feed = Feed()
        pos  = 0
        while pos < len(buf):
            tag, pos = self._read_varint(buf, pos)
            field = tag >> 3
            wire  = tag & 0x07
            if field == 1 and wire == 2:    # ff
                b, pos = self._read_bytes(buf, pos)
                feed.ff = self._parse_ff(b)
            elif wire == 0:
                _, pos = self._read_varint(buf, pos)
            elif wire == 1:
                pos += 8
            elif wire == 2:
                b, pos = self._read_bytes(buf, pos)
            elif wire == 5:
                pos += 4
            else:
                break
        return feed

    # ── Map entry parser ──────────────────────────────────

    def _parse_map_entry(self, buf: bytes):
        """Returns (key: str, value: Feed)"""
        key  = ""
        feed = Feed()
        pos  = 0
        while pos < len(buf):
            tag, pos = self._read_varint(buf, pos)
            field = tag >> 3
            wire  = tag & 0x07
            if field == 1 and wire == 2:    # key — string
                b, pos = self._read_bytes(buf, pos)
                key = b.decode('utf-8', errors='replace')
            elif field == 2 and wire == 2:  # value — Feed
                b, pos = self._read_bytes(buf, pos)
                feed = self._parse_feed(b)
            elif wire == 0:
                _, pos = self._read_varint(buf, pos)
            elif wire == 1:
                pos += 8
            elif wire == 2:
                b, pos = self._read_bytes(buf, pos)
            elif wire == 5:
                pos += 4
            else:
                break
        return key, feed

    # ── Top-level FeedResponse parser ─────────────────────

    def _parse(self, buf: bytes) -> None:
        pos = 0
        while pos < len(buf):
            tag, pos = self._read_varint(buf, pos)
            field = tag >> 3
            wire  = tag & 0x07
            if field == 1 and wire == 2:    # type — string
                b, pos = self._read_bytes(buf, pos)
                self.type = b.decode('utf-8', errors='replace')
            elif field == 2 and wire == 2:  # feeds — map entry
                b, pos = self._read_bytes(buf, pos)
                key, feed = self._parse_map_entry(b)
                if key:
                    self.feeds[key] = feed
            elif wire == 0:
                _, pos = self._read_varint(buf, pos)
            elif wire == 1:
                pos += 8
            elif wire == 2:
                b, pos = self._read_bytes(buf, pos)
            elif wire == 5:
                pos += 4
            else:
                break